from app.services.instructor.courses import (
    list_instructor_courses,
    create_instructor_course,
    get_instructor_course,
    update_instructor_course,
    delete_instructor_course,
    set_course_published,
    create_module,
    update_module,
    delete_module,
)
from app.services.instructor.lessons import (
    list_instructor_lessons,
    create_instructor_lesson,
    get_instructor_lesson,
    update_instructor_lesson,
    delete_instructor_lesson,
    set_lesson_published,
)
from app.services.instructor.quizzes import (
    list_instructor_quizzes,
    create_instructor_quiz,
    get_instructor_quiz,
    update_instructor_quiz,
    delete_instructor_quiz,
    set_quiz_published,
)
from app.services.instructor.challenges import (
    list_instructor_challenges,
    create_instructor_challenge,
    get_instructor_challenge,
    update_instructor_challenge,
    delete_instructor_challenge,
    set_challenge_published,
)
from app.services.instructor.students import (
    get_instructor_dashboard_data,
    list_instructor_students,
    get_student_detail,
    get_instructor_analytics,
    get_course_analytics,
)

__all__ = [
    "list_instructor_courses",
    "create_instructor_course",
    "get_instructor_course",
    "update_instructor_course",
    "delete_instructor_course",
    "set_course_published",
    "create_module",
    "update_module",
    "delete_module",
    "list_instructor_lessons",
    "create_instructor_lesson",
    "get_instructor_lesson",
    "update_instructor_lesson",
    "delete_instructor_lesson",
    "set_lesson_published",
    "list_instructor_quizzes",
    "create_instructor_quiz",
    "get_instructor_quiz",
    "update_instructor_quiz",
    "delete_instructor_quiz",
    "set_quiz_published",
    "list_instructor_challenges",
    "create_instructor_challenge",
    "get_instructor_challenge",
    "update_instructor_challenge",
    "delete_instructor_challenge",
    "set_challenge_published",
    "get_instructor_dashboard_data",
    "list_instructor_students",
    "get_student_detail",
    "get_instructor_analytics",
    "get_course_analytics",
]
